# Generated by Django 5.0 on 2023-12-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_comentariospagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('introduccion', models.TextField()),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='')),
                ('IdBlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.blogs')),
            ],
        ),
    ]
