# Generated by Django 5.0 on 2023-12-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='contenido',
        ),
    ]
