# Generated by Django 5.0 on 2023-12-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_remove_blogs_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
