# Generated by Django 5.0 on 2023-12-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_commentinfo_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmultimedia',
            name='format',
            field=models.IntegerField(choices=[(0, 'Imagen'), (1, 'Video')], default='1'),
        ),
    ]
