# Generated by Django 5.0 on 2023-12-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_delete_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('imagenPortada', models.ImageField(upload_to='')),
                ('contenido', models.TextField()),
            ],
        ),
    ]
