# Generated by Django 5.0 on 2023-12-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_logmultimedia_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmultimedia',
            name='title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
