# Generated by Django 5.0 on 2023-12-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='introduccion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='imagenPortada',
            field=models.ImageField(upload_to='static/assets/img/blogs/'),
        ),
    ]
