# Generated by Django 5.0 on 2023-12-19 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_blogs_introduccion_alter_blogs_imagenportada'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='autor',
            field=models.TextField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
