# Generated by Django 5.0 on 2023-12-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_blogs_autor_blogs_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='autor',
            field=models.TextField(blank=True),
        ),
    ]
