# Generated by Django 5.0 on 2023-12-19 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_profile'),
        ('mainApp', '0012_alter_blogs_autor'),
    ]

    operations = [
    ]
