# Generated by Django 5.0 on 2023-12-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_logmultimedia_title'),
        ('mainApp', '0013_merge_0003_profile_0012_alter_blogs_autor'),
    ]

    operations = [
    ]
