# Generated by Django 5.0 on 2023-12-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_merge_20231219_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographics',
            name='supplementary_Infographics',
            field=models.ManyToManyField(blank=True, to='mainApp.infographics'),
        ),
        migrations.AlterField(
            model_name='infographics',
            name='supplementary_videos',
            field=models.ManyToManyField(blank=True, to='mainApp.logmultimedia'),
        ),
        migrations.AlterField(
            model_name='logmultimedia',
            name='supplementary_Infographics',
            field=models.ManyToManyField(blank=True, to='mainApp.infographics'),
        ),
        migrations.AlterField(
            model_name='logmultimedia',
            name='supplementary_videos',
            field=models.ManyToManyField(blank=True, to='mainApp.logmultimedia'),
        ),
    ]
