# Generated by Django 5.0 on 2023-12-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_merge_20231219_1719'),
        ('mainApp', '0015_alter_infographics_supplementary_infographics_and_more'),
    ]

    operations = [
    ]
