# Generated by Django 5.0 on 2023-12-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_logmultimedia_user'),
        ('mainApp', '0017_commentblog'),
    ]

    operations = [
    ]
