# Generated by Django 5.0 on 2023-12-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_merge_0017_alter_logmultimedia_user_0017_commentblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='infographics',
            name='supplementary_Blogs',
            field=models.ManyToManyField(blank=True, to='mainApp.blogs'),
        ),
        migrations.AddField(
            model_name='logmultimedia',
            name='supplementary_Blogs',
            field=models.ManyToManyField(blank=True, to='mainApp.blogs'),
        ),
    ]
